#!/bin/bash

LEVELS_DIR="/home/oh/contest-18/"
LEVEL_CODE="$1"

LEVELS[0]='OH18_NEXT'
LEVELS[1]='OH18_O0PS1'
LEVELS[2]='OH18_INV4DERs'

check_level()
{
	LEVEL="$1"
	for ((p = 0; p < 2; ++p)); do
		if [[ "${LEVELS[$p]}" == "$LEVEL" ]]; then
			return $(($p + 2))
		fi
	done

	echo "No valid level code."
	exit 0
}

unlock_level()
{
	LEVEL="$1"
	echo "Level ${LEVEL} unlocked!"
	chmod o+rx "${LEVELS_DIR}/${LEVEL}"
}

check_level "$LEVEL_CODE"
P=$?
unlock_level $P
